name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: CheckOut Latest
      uses: actions/checkout@v2
    - name: Clean Install
      run: npm ci
    - name: Run Test + Send Coverage
      env:
        CODECOV_TOKEN : ${{ secrets.CODECOV_TOKEN }}
      run: |
        npm run test:NYC
        npx nyc report --reporter=text-lcov | npx codecov -t ${{ secrets.CODECOV_TOKEN }} --pipe

